server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
       gateway:
          routes:
            - id: saving
              uri: lb://SAVING
              predicates:
                - Path=/savings/a/**

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true
